### ISSUE TITLE
Create wireframes for data input and upload

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#10]

**Comment by signekb** [comment]
As discussed in our meeting this morning, I have found an example of how creating a schema can look using PgAdmin/Postgres @henrik-goul 


![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/2395c532-3dc7-4b33-a2b9-0672c4b8b600)

**Comment by henrik-goul** [comment]
Thank you everyone for your comments and efforts during todays' review. I will absorb the feedback as the next step and update the wireframes before the next review, where I will invite you all again :)

**Comment by lwjohnst86** [comment]
This has been done!
