### ISSUE TITLE
[user-story]: Upload a table definition without a data csv file

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/seedcase-sprout#100]
### What user story would you like to add?

As a (Data) Administrator, I want to be able to complete a table definition (the column part) off-line and upload it, bypassing the 'upload the data csv' step.  This would be useful if I was given a sensible column description with my data (eg registry data), and save me having to copy and paste the descriptions into an online form.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by K-Beicher** [comment]
A good example would be the definition documentation that comes with Synthea data (see the file in the Data Repo), it seems a waste of time to copy each description into a form online, when I can edit a spreadsheet with the last few columns (like allow missing and allow duplicate).  A similar function exists in RedCAP, I've found it very useful there.

**Comment by signekb** [comment]
Low priority.

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
