### ISSUE TITLE
Decide on frontend (UI) framework

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#11]
I have tried three different UI frameworks, that would suit seedcase
- Bootstrap 5. Seems to have the best integration to Django. https://getbootstrap.com/docs/5.0/examples/ 
- Bulma. Simple css-only framework. You just need to add css classes. Here are some examples of pages made with bulma: https://bulma.io/expo/
- Material Design. Material design is the most "modern looking" of the frameworks: https://materializeweb.com

**Comment by philter87** [comment]
Let's try out with Material Design

**Comment by philter87** [comment]
https://www.beercss.com/. The name is weird but it seems to implement "Material Design 3"

**Comment by lwjohnst86** [comment]
Closed by https://github.com/seedcase-project/design/pull/45
