### ISSUE TITLE
Create draft for UI look and feel

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#12]

**Comment by henrik-goul** [comment]
I have scheduled to kick-off work on the UI look and feel with the visual designer (Nicklas) on Monday February 5th :)

**Comment by henrik-goul** [comment]
Updates have been made to the bright green colour now, so I would very much like your feedback on this once again @signekb @K-Beicher @lwjohnst86 @philter87 :)
https://www.figma.com/file/czeKwMxVLKPNQDX42eiTxq/Wireframes?type=design&node-id=441%3A1062&mode=design&t=wpuxC372b5gciHv2-1

**Comment by henrik-goul** [comment]
Thanks for the feedback everyone. I have taken note that we want to be able to play around with the colour nuances a bit before settling on the final green colours, so I will make sure to set up an example screen that allows us to test this out :)
I have scheduled time with my UI designer colleague on Monday to help me set this up for us.

**Comment by henrik-goul** [comment]
UI screens for 2.1, 2.2 and for the login screen is now available for review here:
https://www.figma.com/file/czeKwMxVLKPNQDX42eiTxq/Wireframes?type=design&node-id=1111%3A3816&mode=design&t=ga9F7K9YhekH2Hw2-1

I will give a short introduction in FIgma on how you can change the colour styles in case you want to play with it a bit yourselves :)

**Comment by lwjohnst86** [comment]
What has been done so far is a great starting place, so considering this closed 🤩
