### ISSUE TITLE
Discussion: Should we have one or more test catalogues

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/seedcase-sprout#120]
Kris will work on first draft of this

**Comment by lwjohnst86** [comment]
Missed out on a lot because of my teaching! Could you expand on what is meant by "test catalogues"?

**Comment by K-Beicher** [comment]
I have worked with two types of test catalogues, although one may not actually be a test catalogue in the true sense of the word.

The standard test catalogue is a collection of things that you have agreed that you should test against every time you build something.  A very commonly used one is a list of different types of string or number input which you run against any input field in an app, making sure that it can handle various special characters, how it handles a float with , or . and so on.  I would highly recommend that we pick a catalogue for each of our data types so that we ensure that we test for the same things every time.

The second catalogue type (and this is where I don't know if it is the correct name), is a list of common things a user might be tempted to do at various points in the system.  I used to create them based on flow charts and wire frames, so that the developers could automate as much testing as possible during development.  Seedcase may not be a system which is complex enough to warrant this (at least yet), but it is a help if you go back and re-develop parts of a system, where you can then go through the catalogue of testing to see if a change could affect anything further down the line, and if so, how you ensure that you don't build something that will make other parts of the system unusable.

Open to comments from the rest of you guys(@seedcase-project/developers), my suggestion would be that we look for the first type, and keep the second type at the back of our minds for now.

**Comment by lwjohnst86** [comment]
I think this is closed given what we're doing now.
