### ISSUE TITLE
Discussion: should we extract 'allow' values from the initial csv file

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/seedcase-sprout#121]
Kris will work on first draft of this.

**Comment by K-Beicher** [comment]
It is possible to extract information from a csv regarding whether a column is completed or not, thus extracting potential information on the NULL/missing value status of a column. This will help the user when setting up a table, but may also lull them into believing that all is well.

There are two arguments to this which depends on whether or not we believe that a user will read the documentation or not.

If the user reads the documentation prior to using the 'extract my table structure from my csv' function and understands that all fields which should allow a missing value should be checked, as the fields with missing values may well be in a part of the csv which wasn't part of the analysis. They will then read down the list of fields and manually change any that are wrong.

If the user doesn't read the documentation and believes that the system will always correctly analyse the fields, then they may have a problem when they come to upload their data. If a field is set to not allow missing values then the upload will fail, if it should in fact have allowed it. This in turn means that the administrator will have to go back to the table set-up and read through all the columns (arguably they should have done this already), and the data uploader may potentially have to wait until this has been done before trying again.

There are two solutions as I see it. We analyse the data presented to us, and set the values based on that, because we believe that the user will read the instructions. We don't set the value, but provide a Select All, option at the top, so the user can set all fields to either allow or not allow missing values, because we don't think they'll read the instructions.

I think this is mainly for @lwjohnst86 to ponder, which group do you think our users will fall into?  The rest of you guys (@seedcase-project/developers) are more than welcome to add thoughts and solutions as well.

**Comment by signekb** [comment]
Either way, I think it might be nice to add a "caution"/"information" text on the UI of the extraction page (potentially shown with a hover over a (?) button), so whatever we decide to do is easy for the user to understand/read up on.

**Comment by lwjohnst86** [comment]
I think in general we assume the user has not read as much on the documentation as we'd like. I know I don't always read documentation before using and I doubt I'm an atypical user here.

But, related to the topic:

> "We analyse the data presented to us"

We shouldn't process all the rows in the data given to Sprout to extract the data structure. That's a very inefficient way of checking data types/structure. I think providing the option to "select all" would be useful though!

@henrik-goul that's something to add to the wireframe!

**Comment by philter87** [comment]
Both solutions are technically possible - I don't know which to choose. 

I think we will likely need to support deletion of rows with a "master select" later, but I don't know if it intuitive to change "Allow Empty" like this

**Comment by henrik-goul** [comment]
@philter87 No problem, thanks for sparring with me though :)
I suggest that we go for a "master select" option and work it from there to make it intuitive.

**Comment by K-Beicher** [comment]
Considering that we have now moved away from displaying these fields in either overview should we just leave these to a future page where anyone who knows what these fields can do, can get to manipulate them? 

My suggestion would now be that we allow missing for all except for the ID field. Which just leaves the question of where to indicate which field is the identifier in a table...

**Comment by signekb** [comment]
@K-Beicher Yeah, I think we should leave this issue for now and return to it when we are ready to include more advanced options in Sprout
