### ISSUE TITLE
Managing Python dependencies

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#13]
There are several ways of managing dependencies. Seems poetry is well regarded, [comparisons here](https://ritza.co/articles/gen-articles/pipenv-vs-virtualenv-vs-poetry-vs-pyenv-vs-pip/). Thoughts?

**Comment by philter87** [comment]
I think you are right. Poetry is the way to go, if venv+pip is not good enough, but I usually use venv and pip. But poetry is used quite a lot and it often pops up when I am investigating the different options for deploying and hosting a Django app
