### ISSUE TITLE
Investigate: Could we use or build off of sheepdog?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#14]
@rqding This [sheepdog](https://github.com/uc-cdis/sheepdog) package has some similarities to this project. Could you look into how it is similar, what we could draw inspiration from, and if forking it would be a better place to start?

**Comment by signekb** [comment]
Sheepdog is a part of gen3: https://gen3.org/resources/user/

**Comment by signekb** [comment]
Things from gen3, I think we could use: 
- They visualise how the data is linked (using nodes, see screenshot below). Doing something similar, but maybe in a different way, could help users keep an overview on how data is linked
<img src="https://github.com/seedcase-project/seedcase-sprout/assets/40836345/db913737-009e-48f8-ae47-ef86e0feb68c" width="300" height="300"> from [this tutorial](https://www.youtube.com/watch?v=QxQKXlbFt00)

**Comment by lwjohnst86** [comment]
Given our direction, this doesn't make sense. Closing.
