### ISSUE TITLE
No date type in pandas

### ISSUE THREAD

**Issue by philter87** [seedcase-project/seedcase-sprout#146]
There is no date type in pandas, so what should we do about it?

1. We can simply skip the "date" type as this is a subtype of datetime. If people need a date it will just be stored as datetime with time=00:00:00
2. We can convert to a "python date" if all have time=00:00:00.  The dtype will be 'object', so we might need an extra attribute to identify date-columns
3. We can keep the datetime, and then simple add an attribute to the column identifying it as dates. (datetime64 is 8 bytes vs date 32 bytes)
4. Later, when the pandas dataframe is converted into a list of "ColumnMetaData", we can try to detect if the datetime is actually a date (all have time=00:00:00) and then store this information in the database
5. Not use pandas? Probably a bad solution, because we might need pandas for other stuff later and then it would be nice to have aligned the pandas types with the types in sprout)
6. ?

**Comment by lwjohnst86** [comment]
Solved with #147 by using Polars.
