### ISSUE TITLE
Discussion: Use Polars instead of Pandas for getting data types?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#147]
@signekb suggested Polars. Seems it might be better for our purposes, at least for getting the data types: https://docs.pola.rs/py-polars/html/reference/datatypes.html even has time and date types!

**Comment by philter87** [comment]
You are right! It seems like a perfect solution and it has parquet support

**Comment by signekb** [comment]
Nice. Where does this leave us with #126? Should we review and then @philter87 will work on a polars solution instead?

**Comment by philter87** [comment]
No, I don't think you need to review it - I have turned it into a draft. I am investigating polars

**Comment by lwjohnst86** [comment]
Based on multiple discussions, it seems we all agree that Polars will be better suited for our purposes (at least right now).
