### ISSUE TITLE
[bug]: Seedcase icon is not shown in nav bar (using link from README)

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#152]
### Steps to reproduce

1. Click on link in the README.md ([...] [app](https://seedcase-sprout.fly.dev/))
2. See the missing icon in the nav bar
![Screenshot 2024-02-12 at 09 16 02](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/66c5f22f-fe95-42c4-a62c-607ce3950996)

### Expected result

The Seedcase icon should be shown. 

### Actual result (the bug)

It is not shown.

### Severity/Priority

2: Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lwjohnst86** [comment]
This was closed in #175
