### ISSUE TITLE
Rename folders to `config` and `sprout`

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#156]
The main `seedcase_sprout` folder contains the Django config information, so maybe call it `config`? And then call `app` into `sprout`? @seedcase-project/developers

**Comment by signekb** [comment]
I have been looking for a standard or convention of how other's do this and it seems like there are many different ways to do it. I like your suggestion (I think it's a lot more intuitive than what we have now)! 
I'm just not sure if it could be confusing for other's who know the folder structure and naming from the `django startproject` command, where the root and the project has the same name?

**Comment by lwjohnst86** [comment]
Yea, it bothers me a lot that there are so few strong conventions/standards that make a lot of sense... Boggles my mind...

And yea, another way of thinking of it is that sprout, etc are packages that work together to complete a set of tasks related to working with data. This is the ["Unix philosophy"](https://en.wikipedia.org/wiki/Unix_philosophy) way of building programs and why I wrote the poly-repo decision post. Also why I'd like to eventually have each programs to have CLIs of some type.

**Comment by signekb** [comment]
Uhhh, nice with CLIs as well. I don't think that you have mentioned that to me before. 
Another question: Do we intend each repo to only include one app? Like, could it make sense to divide `sprout` into two apps:`metadata-import`/`metadata-extraction` and `data-upload` ?

**Comment by philter87** [comment]
I think renaming would be great. 

Adding more apps would make sense for some things. For instance, login would fit nicely in an app. My initial though is that metadata-import and data-upload are too connected to divide in multiple apps, but maybe you can change my mind.

I personally dislike splitting sprout into multiple repos at this point. Maybe later, when we are more settled on the structure. If we do it now we will often need to touch two repos simultaneously and hence two branches (one for each repository). This will give a bad developer experience with many context switches. Furthermore the github actions will become weirdly complicated as we need to checkout two repositories. Or we would need to publish packages to pip and figure out how to do versions that not necessary align: one is 1.0.1 and another is 0.0.1.

Furthermore, it is currently hard to draw a clear line/boundaries between the apps. It will be fairly simple to adjust the boundaries if the apps are part of the same repository, but a annoying if it is part of two repositories. 

I have bitter experience with dividing an application into multiple repositories. I think we should divide into different apps, but keep one repository until we know where to put the boundaries.

**Comment by signekb** [comment]
Think that sounds good @philter87. I would also definitely say that `sprout` should remain in one repo. And I'm also fine with keeping it as one app for sprout for now and then one for login.
