### ISSUE TITLE
Discussion: Postgres vs Parquet, which to implement right away?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#157]

**Comment by K-Beicher** [comment]
In my view definitely postgres, as that can also handle user security.  I'm also worried that if we save data in parquet then we'll have a job converting it back into for instance csv, if a user would like to export their data in a format that can be read my another system.

Does anyone know how STATA, SPSS, R and Python deals with parquet?

**Comment by lwjohnst86** [comment]
@K-Beicher yea, I think that might be a good starting point. Saving between Parquet and CSV is very easy, so it isn't an issue.

R and Python handle Parquet just fine, since there are packages available to do that. SPSS I think can handle it, SAS I think so too. Stata unfortunately doesn't.

**Comment by signekb** [comment]
Kris and Luke: We want to handle files in a database structure (bc we can't handle users in parquet files, for instance).
Philip: Will check up if polars can handle this.

**Comment by philter87** [comment]
So there are many considerations in this discussion and I am not sure where to start: 
- **CSV, parquet or database tables**. We are using polars to parse a CSV. Polars is able to write to CSV, parquet and surprisingly non-existing database tables with: `df.write_database(table_metadata.name, database_url, engine="adbc")`. My biggest argument for not using a database for the actual data was the complexity of dynamically creating tables. But this is not an issue with polars (and it works for both sqlite and postgres, so we can run it locally without spinning up a postgres database)
- **Exporting to CSV**. Polars can easily create CSVs no matter if it is based on a parquet file or a database
- **Security**. I am not too concerned with the security aspect of having files on the server (this was mentioned in #62). The web app will decide what people can view and edit. Normal users will not be able to directly see or edit these files. The admin might be able to see the files directly on the server, but the admin should not make manual corrections to these
- **Performance**. I ran some small tests comparing sqlite vs parquet with a big CSV (142MB and 6.5 mio rows).
  - **Speed**: SQLite took 5 seconds and parquet took 0.8 seconds to persist the CSV
  - **Size**: SQLite uses 160MB and parquet uses 18 MB
- **Appending data**. With SQLite it is more obvious to add new data to a table. This is not possible natively with parquet files. You would need to have multiple files or merge files
- **Joins?** Using a SQL database will have the possibility to do joins. I think "joins" are too complicated for normal users, but if this is needed then we need to use a SQL database
- **Admin access**. The admins will be able to view the data in the database - this will not be smooth with parquet files. Again, I don't think this should be the way to access the data, but I think I have heard this as a requirement

**Comment by lwjohnst86** [comment]
Focus on implementing Postgres right now.
