### ISSUE TITLE
Function to convert extracted metadata column names into appropriate snake_case or similar

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#159]
During the metadata extract phase, having an (default) option to convert column names to `snake_case` (one of the best for readability) would be great. So that we can enforce/encourage following better practices.

**Comment by signekb** [comment]
We need a new column in the ColumnMetadata with the original column name. So now we have three: 
- original column name (what was originally in the csv)
- machine readable column name (snake_case as default)
- human readable column name

**Comment by signekb** [comment]
This function will do the trick, found [here](https://www.w3resource.com/python-exercises/string/python-data-type-string-exercise-97.php): 
```
def snake_case(s):
    # Replace hyphens with spaces, then apply regular expression substitutions for title case conversion
    # and add an underscore between words, finally convert the result to lowercase
    return '_'.join(
        sub('([A-Z][a-z]+)', r' \1',
        sub('([A-Z]+)', r' \1',
        s.replace('-', ' '))).split()).lower()
```
