### ISSUE TITLE
In wireframes, include option to *not* convert to snake case for metadata extraction

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#163]
When they upload the csv file to extract the metadata, the extract metadata columns should be converted to snakecase. So maybe we have two columns, one for the original column names and the other for the converted names? And have an option to not convert them?

Snake case is the way of naming variables/columns in data and in programming languages. It is in the form of `snake_case` or `this_is_the_name`, where everything is lowercase and a `_` replaces spaces.

There should be two columns then:

| Original Column Name | Converted (or new) Column Name |
|--|--|
| Age at visit | age_at_visit |

**Comment by henrik-goul** [comment]
Something along these lines @lwjohnst86 ? :)


![Image](https://github.com/seedcase-project/seedcase-sprout/assets/152619915/e9633a20-2cdc-4f96-97ec-79b5b5de6152)

**Comment by lwjohnst86** [comment]
Mmm, more like, a "global" option to say "convert or not". But, we're actively discussing how this should look like, so maybe hold off on doing any work on it.

**Comment by henrik-goul** [comment]
@lwjohnst86 Thanks for reviewing. Alright, I will hold off a little bit on this. Let me know whenever you want me to chime in again :)

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
