### ISSUE TITLE
Discussion: How to let user bulk add metadata external from Sprout?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#168]
There's got to be a way for the user to save their metadata, so that they can stored it to process it in other ways or maybe to upload the metadata separately. How should they do that?

**Comment by signekb** [comment]
We have added that the users can download the table metadata after creating the table in the user flow, see screenshot below. 
I guess we could also add metadata extraction to wireframe 1 where users can examine existing tables?

![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/14e33fbd-4162-4437-8628-42c2503ba245)

Or did you have something else in mind?

**Comment by K-Beicher** [comment]
My suggestion would be a download button on the page I've created to allow them to review the data.  That would be an easy solution.

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
