### ISSUE TITLE
Use `polars.scan_csv()` and/or dialect detector combined with `separator` to read CSV files without the for loop

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#187]
Detect the dialect and use that detection directly in the `read_csv(separator = )`. There's also a function called `scan_csv()` which might be useful for our purposes of only looking to get the metadata. 

See https://github.com/seedcase-project/seedcase-sprout/pull/154#discussion_r1492878137_

**Comment by philter87** [comment]
I already tried this approach (using the separator and eol_char) but there are more aspects to a CSV dialect. 
For instance, polars.read_csv (or polars.scan_csv) is not able to parse this dialect: 

first_name,    second_name,    age
Philip,           Christiansen,       36

**Comment by philter87** [comment]
Okay... I may have found a solution. If we use pyarrow it seems to solve the issue. I though I already tried, but some combination of arguments may have disabled it.

`read_csv(csv_file, use_pyarrow=True, separator=';')`

`use_pyarrow: Try to use pyarrow’s native CSV parser. This will always parse dates, even if try_parse_dates=False. This is not always possible. The set of arguments given to this function determines if it is possible to use pyarrow’s native parser. Note that pyarrow and polars may have a different strategy regarding type inference.`

However, it is not possible to use pyarrow for polars.scan_csv. But I don't think it would add a lot of benefits to this particular case: Reading 1000/500 rows is very quick and we need to read everything in this chunk anyways

**Comment by philter87** [comment]
Another issue though... It is unable to handle initial whitespace for booleans (it might be okay, because we are already have custom logic for handling these). I the example below the column 'b1' is derived as strings:

`

            "i1;    f1;     b1;     s1\n"
            "10;    5.3;    True;   Hi\n"
            "11;    1.0;    False;  Hello\n"
            "12;    1;      False;  Man"
`

**Comment by philter87** [comment]
So... We should not enable use_pyarrow (it doesn't work when n_rows is specified and it is unable to handle initial whitespace for booleans).

But we could rely on polars to read and strip the values as csv.reader is slow (the for-loop is not slow, but together with 'csv.reader' it is). I have tried to read a CSV file with 6 mio rows:
- csv.reader takes 2.5 seconds to read the file. And 10 seconds to read and write to a new file
- polars.csv_read takes 0.25 seconds to read the file. And 1.5 seconds to to read and write to a new file with trimmed values


**NOTE** The performance is not a problem when reading 1000 rows to derive the schema, but we need a solution when we need to validate the entire dataset.

**Comment by lwjohnst86** [comment]
This has mostly been resolved in #154
