### ISSUE TITLE
Create User Stories from Documentation

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#19]

**Comment by henrik-goul** [comment]
Joint session with @signekb has been scheduled for Monday, December 11th.

**Comment by signekb** [comment]
In the meeting, we didn't get to user stories, but went through the diagrams Kris and I have created #22 and talked about what we think will be included and the potential flow in sprout. This (hopefully) helps @henrik-goul with creating wireframes #10

**Comment by signekb** [comment]
Intention: Break down screens and functionality. 
It's not needed currently.
