### ISSUE TITLE
Discussion: Naming scheme for HTML files and paths within app

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#196]
I don't feel we have a strong scheme for how we name the Django HTML templates. What are some good naming schemes here? How should the file path "API" be structured. This I think should have a design to it as well.

**Comment by signekb** [comment]
I like it! With sprout instead of import 👌

**Comment by K-Beicher** [comment]
I like the sprout version as well.

**Comment by K-Beicher** [comment]
So probably go with the /sprout/ solution.  @lwjohnst86 Should we convert this into a decision writing issue, and/or implement it?

**Comment by signekb** [comment]
Maybe we should actually change `column_review`to `review_columns` so it fits with the rest with verbs first, like `derive_columns` and `upload_data`? Aligning with that, should `existing_tables` be `review_existing_tables`, or am I taking it too far?

Alternatives could be to lose the verb like so: 
- **derive-table-columns** -->  **column-extraction**
- **column-review**** --> **column-review** (same)
- **existing-tables** --> **existing-tables-review**
- **upload-data** --> **data-upload**

**Comment by K-Beicher** [comment]
I suspect we'd be grateful down the line if we keep the option for a verb, I'd be happy to change mine to comply and use the 'verb first' approach going forward.

**Comment by philter87** [comment]
I actually do like the "verb-first" - I don't know why 🤔

**Comment by signekb** [comment]
Alrighty. I'm fine with either, as long as we are consistent 🚀

**Comment by lwjohnst86** [comment]
Thanks for all the input! I've been thinking about this a lot too, and going with the "verb" approach and in line with CRUD (Create Read Update Delete) of the core "language" of connecting with databases as well as the equivalent HTTP verbs (GET, POST, PUT, PATCH, and DELETE), I thought of a couple of "actions" and "objects" we have/work with:

- Objects: data and metadata
- Actions: create, view (or get), edit, upload

So something like:

- `/upload/data/` and `/upload/metadata/` for landing pages, and `/upload/data/<table_id>` and `/upload/metadata/<table_id>` for individual tables that already exist
- `/create/data/` and `/create/metadata/`
- `/view/metadata/` (to show list of all tables to select) and `/view/metadata/<table_id>`
- `/edit/data/<table_id>` and `/edit/metadata/<table_id>`

Thoughts?

**Comment by philter87** [comment]
`/projects` shows all projects for the user
`/projects/<id>/tables` shows all tables for a project
`/projects/<id>/tables/<id>` shows the table?
`/projects/<id>/tables/<id>/create` shows the table?
