### ISSUE TITLE
Discussion: Investigate and draft documentation on login and authentication

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#2]
**Login and authentication described in Runtime view in the design docs:**
https://github.com/seedcase-project/seedcase-project/blob/66213743aae1a71186a1b7147826407f85f09945/design/software-architecture/runtime-view.qmd#L10-L17

Should be moved to Sprout repo and fleshed out into more detail.

Django out-of-the-box id

**Identification**: 
- ORCID? #3 
- MitID?

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
