### ISSUE TITLE
[bug]: "extracting metadata" progress bar in file-upload remains after clicking back from 404 page 

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#201]
### Steps to reproduce

1. Create new table and fill in dialog box details.
2. Upload file. It will pop up with a "extracting" popup progress bar.
3. It will move into extracting metadat.
4. Click back. The popup progress bar is still there. It should restart.

### Expected result

The popup progress bar for extracting metadata should not be there after clicking back.

### Actual result (the bug)

But the popup is still there after clicking back from the next page.

### Severity/Priority

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by philter87** [comment]
Unable to replicate the error. The loading bar is not showing when I go back (I have tried both with and without an error)

**Comment by signekb** [comment]
I can't replicate it either :)

**Comment by lwjohnst86** [comment]
Interesting, I tested it on Chrome and it doesn't show the bug, but on Firefox, it does......

**Comment by philter87** [comment]
Okay, I have been able to replicate now on firefox. I will try and fix it
