### ISSUE TITLE
[feature-request]: Embed PlantUML in (quarto?) markdown files

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#21]
### What feature would you like to request?

Instead of having puml files and having to export the diagrams as pngs to be able to include them in markdowns, we should find a way of embedding puml files in markdown files. 

### Optional: Suggest a solution

I just found this [github action](https://github.com/marketplace/actions/plantuml-for-markdown) that embeds plantumls in 
markdown files. However, this might not work for qmd-files. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lwjohnst86** [comment]
There's already an issue for that: https://github.com/seedcase-project/team/issues/77 We can insert puml directly into markdown, so we don't need the puml file, nor the png :stuck_out_tongue_closed_eyes: just have to implement the filter to insert the diagram into the rendered html (from md).

**Comment by signekb** [comment]
Ah!  Sorry about that. I'll just close this then 😛
