### ISSUE TITLE
Create `projects id metadata create` page

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/seedcase-sprout#210]
There should be two actions at the bottom of the page, one for save and continue editing and one for save and close.

**Comment by K-Beicher** [comment]
This is running into a problem with the django framework (I think), where it won't allow a Save unless all fields are completed.  I'm going to pause this until we have a solution for it.

**Comment by signekb** [comment]
This is on hold until the team has agreed on the design, see issue #397.

**Comment by lwjohnst86** [comment]
@signekb is doing this currently.

**Comment by lwjohnst86** [comment]
This is duplicate of #397
