### ISSUE TITLE
Discussion: Would it make sense change the "Create table" flow slightly by removing the "Create table dialog"?

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#214]
As discussed at today's update meeting (29 February), the current flow for creating a new table includes quite a lot of clicks. 
Could we simplify the flow somehow? Potentially by making the "Create table dialog" a part of the file upload page?

As Henrik said [paraphrasing from memory here], the goal is not solely decreasing the numbers of clicks, but to create an intuitive and supportive flow that is efficient and easy to navigate. 

Thoughts? Alternatives? 
@philter87 @lwjohnst86 @K-Beicher @henrik-goul

**Comment by henrik-goul** [comment]
Just to make sure I understand the suggestion @signekb 
Are you suggesting that we let the user press "Create" on screen 2.1, which takes the user directly to screen 1.2?
And thus making the dialog described in 1.1.2, 1.1.3 and 1.1.4 obsolete? :)

**Comment by signekb** [comment]
@henrik-goul Yes, that's a suggestion. Please chime in if you have other ideas of making the flow a bit less clicking-heavy :)

**Comment by signekb** [comment]
Question is: *Should* we make it more efficient?

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
