### ISSUE TITLE
Discussion: Naming practices of functions

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#224]
The old saying that "the hardest thing in programming is naming things"... which I definitely feel is true! I don't know about the others, but it would help me if we had some type of structure or "guide" on how we name functions and how we name files and folders. This is related to #196 but for Python code.

**Comment by signekb** [comment]
This is tied to the discussion of #196 and closed with that.

**Comment by lwjohnst86** [comment]
Reviewing the code more and thinking about this more, this isn't actually closed by #196, though it is a part of it. I'm going to reopen, change the title of the issue, and maybe split this out into other issues, for functions, for files, and for folders.
