### ISSUE TITLE
Discussion: pytest vs Django built-in unittest

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#226]
I'm generally not happy with how Django (actually unittest) structures and runs tests. Looking into this a bit, my impression is that pytest (pytest-django) is generally better. But let's discuss this a bit here.

Both the classes and the output of the tests (it would be nice with more structure)

**Comment by signekb** [comment]
Philip mentioned the use of fixtures when testing https://github.com/seedcase-project/.github/pull/105#discussion_r1547558111
