### ISSUE TITLE
Potential alternative design of column review wireframe (1.5)

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#233]
Based on the user test/demo on Monday, 4 March, we might want to reconsider the table view of the column review wireframe. 
The user mentioned that they found it confusing that the rows in the view described the columns in the table. 

@K-Beicher mentioned that she has experience with a view looking more like a list (see image below). 
Could you make a draft of something like that instead, @henrik-goul? :)

![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/1e32d9f5-253e-4fdb-a8a1-cf9dfc1599b5)

**Comment by lwjohnst86** [comment]
This has been redesigned/considered in the new flow @signekb has been working on.
