### ISSUE TITLE
Discussion: Should we rename column "original name", "header" and "title" to something more intuitive?

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#234]
I think that I'm not alone in never being able to remember which one is the "machine readable" one, and which is the "human readable" one. 

Talking to @K-Beicher about some of them, we have the following suggestions:
`original column name` --> `extracted column name`
`title` (the human readable name) --> `display name`
`header` (the machine readable name) --> `variable name` ?? 

Please chime in with ideas to make this more intuitive @philter87 @lwjohnst86 @K-Beicher 

(Assigning myself as the one to ensure this discussion moves forward and will be resolved)

**Comment by philter87** [comment]
Hmm... It is tricky and I am just brainstorming a bit here:

original column name --> extracted csv header
title --> display name
header --> machine readable name

And I can't let go of the thought that three is too many...
What if the machine readable name is just a number?

**Comment by signekb** [comment]
Yes, we need to show it, so they can change it if they don't want snake case :)

**Comment by philter87** [comment]
Ahh... Now I remember... at least part of that discussion. 

But why is it again that the user needs to decide if the machine readable name should be in snake case or not - it seems like a too technical detail. We will likely use these variables as columns in a database table or a parquet header, so there need to be some restrictions

**Comment by lwjohnst86** [comment]
Hmm, that's a great question. I personally would say that all variables be named as snake case, but there are some naming standards out there (e.g. CDISC and their [SDTM](https://wiki.cdisc.org/display/SDSVAR/SDTM+Variable+Definitions+-+Batch+2+2021+Review) standard for medical/clinical trial data) have some pretty.... odd, ugly, and non-descriptive/intuitive ways of naming variables, but it's a standard that you have to follow if you do clinical trials for drugs. So we need some way for the user to select on a naming scheme.

**Comment by philter87** [comment]
I see... But it might still break our application, so we will need to figure something out

**Comment by lwjohnst86** [comment]
What about if we internally use a GUID/UUID for column names, include metadata about the "export name", "display name", and "original name"? I know it gets to be quite a bit, but unfortunately, we can't avoid having different standards for naming variables (nor should we force it).

**Comment by lwjohnst86** [comment]
@K-Beicher How does Postgres handle these types of things? Is there a column name label that can be part of the metadata, so people looking directly at the data can see the "machine-readable" column (UUID) but also see what it could be exported as?

**Comment by lwjohnst86** [comment]
Or, maybe what if we do this:

1. Metadata extraction, set a UUID for the column that only Sprout sees (and maybe the admin). Or force the use of snake case.
2. Extract the original column name that we store internally for later reference when people upload similar looking data.
3. Get user to write a display name for that column that has the internal UUID/snake case, that will be displayed in all user-facing cases.
4. When exporting to CSV (this is in another application I think), provide the option to convert to other types of variable naming schemes.

**Comment by philter87** [comment]
Yes, something like that.

And I want to adjust some of my previous comments.

I am okay with many names for a column, I am just concerned about how many we show to the user. 

We should show a maximum of two to the user in "view 1.5":
- **display names**. 
- **"original csv header names" or "metadata extraction name"** (but grayed out as Kris is doing now). I think these are important as they will likely be used again, when the user imports data in a new CSV. But we could also show these in the advanced view of 1.5?

Then we can have more names (potentially many), but these should be hidden by default in "view 1.5". 
- machine readable name. Either forced snake case name (or a uuid or the id of the ColumnMetaData object). This should be hidden to the user except if they access the database directly. I like snake case names, but we need to be careful not to change these (as they are used as database table names and/or parquet headers)
- Export column name. Could be shown in the advanced view or at a different "view" when user wants to export the CSV (like Luke said in the previous comment)

**Comment by signekb** [comment]
I think that it makes sense to show the user the extracted column names greyed out, so they can see the original name after they have altered the display name.

**Comment by K-Beicher** [comment]
Agree, the way I envision this working in a database is to have a row in the system db for each column of research data which contains the machine_readable name.  

Then a second table sitting with the research data itself which holds as many or as few of the names that we decide to employ (including the original_name).  When we get to the extraction this will be the table that generates the csv headings, no reason (as far as I can see), that we can't leave it to the user to tick which of the headers they would like to use in any given extraction of research data.
The only thing to bear in mind, is that the table in the system-db can't be modified, so we can only keep one column-header-name in there.

**Comment by lwjohnst86** [comment]
I think the "exporting" part of this discussion is out of scope for Sprout (only aim of Sprout is to store data in a structured/modern way).

As long as there is the machine readable name and a human readable name, we can generate snake case, etc in the software that aims at exporting data.

**Comment by signekb** [comment]
@seedcase-project/developers 

I see that this discussion has gone beyond the issue (which makes a lot of sense given the discussions we have had lately). 
But, for the purpose of this issue: What do you think of renaming "original name", "header" and "title" to: 

original column name --> extracted column name or extracted header?
title (the human readable name) --> display name
header (the machine readable name) --> variable name or machine readable name?

**Comment by lwjohnst86** [comment]
@signekb that works for me. For the `variable name` one, would you think `table_variable_name` or `database_variable_name` is more explicit? Since this is for us only anyway, would `variable_name` be clear enough?

**Comment by signekb** [comment]
Great. I actually think that, if it's just for us, then `machine_readable_name` might be the one to go with, since that's what we currently call it when we can't remember if it's `title` or `header` anyway?

Just a short recap: These names are defined in the `ColumnMetadata` model like so:
```
class ColumnMetadata(models.Model):
    """Model representing the metadata of columns."""

    table_metadata = models.ForeignKey(TableMetadata, on_delete=models.CASCADE)
    original_name = models.CharField(max_length=1000)
    name = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    [...]
```

and they would be changed to: 

```
class ColumnMetadata(models.Model):
    """Model representing the metadata of columns."""

    table_metadata = models.ForeignKey(TableMetadata, on_delete=models.CASCADE)
->  extracted_name = models.CharField(max_length=1000)
->  machine_readable_name = models.CharField(max_length=200)
->  display_name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    [...]
```
(arrows added for emphasis on changed lines)

**Comment by signekb** [comment]
@seedcase-project/developers 
I guess this ties into the discussion we had at today's user test. My takeaway is that whether all of these should be included and/or shown at metadata creation is still up for debate, but I'll rename/align them with these names. @seedcase-project/developers , agree? :)

**Comment by philter87** [comment]
Yes, I like the names you suggested. And then can figure out what we do later.
