### ISSUE TITLE
Discussion: How do we implement multiple projects/instances?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#239]
Right now, when the user opens Sprout, they see the landing page for importing a dataset that was created from a specific study/research project. But how will it work another users, from another research/study project, wants to upload data into a "study-specific instance/project" that holds all data collected for that project (and not connected to other projects)? This is something I don't really know how it will look like. 

I assume we might need an initial landing page of "create project" and "select existing project", from there they can create tables for that project and be owners for it and assign permissions as needed there. 

Then the question expands into, where is the data for each "project instance" stored, and how is it separated?

@philter87 I've assigned you to this since you might have more ideas about it.

**Comment by philter87** [comment]
I think it is fairly easy to imagine a solution in the web app. Every table is linked to to a project and users are assigned to projects with certain permissions (write, read, etc )

What is unclear to me is how many should be allowed direct access to the database (and the server)? And whether this access should be handled by the web application.

##  Scenario 1: Direct access to database is not handled in the web application 
If there is only one admin in a seedcase instance, then everything is nice and simple. This person have access to everything in the database  and we don't need to align with the users and roles in the web application (The in a Django web application is defined in the tables auth_user, auth_group, etc).

The admin can manually give access to other people in the database by creating users and roles in the database. But these are not automatically aligned/synchronized with the users and roles in the web application.

Every project could have their own database "schema" to easily divide the database in multiple parts

## Scenario 2. Users and roles are synchronized between the app and the database
If there is an admin for each project, and they should have direct access to see certain parts of the database, then it becomes more complicated! The admin users in the web application would need to get "synchronized" with the users in the database (and potentially the server somehow).

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
