### ISSUE TITLE
Discussion: Table vs data (re-visited) and column vs variable

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#251]
During a discussion after the update meeting, we got into a discussion about table vs data. We originally decided on table vs using schema's, but didn't really decide on data vs table. Table might not be very clear to users (table in a report?) and (in my experience) isn't a commonly used word for researchers. Data is very commonly used but of course is more vague.

Another idea is "data structure" or "dataset" or "data definition" or "data description" .

Also part of this discussion is "column" vs "variable". Column (as seen in the "metadata review" page) could refer to the column of *that* table (the HTML page). Variable is a bit more commonly used, since it refers to the entity used in statistics. But it might not be clear what it is too.

Add thoughts here.

I think for both, we should ask other researchers about it, since we all might have very different experiences.

**Comment by philter87** [comment]
So I was talking to my colleagues about our discussion and they also suggested "data structure" and "data definition" as names when we need to address the schema of the data (I have added these to the description above as well).

I know, that you (@lwjohnst86) have a better understanding of what researchers know, but for me it just seems as a natural thing. I know that it might not be a natural word to use for data in R or python, but it is fairly common to use as a type graph. Like the picture below:



![Image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/f793b26f-9190-47a2-b5fb-d939bb739730)

**Comment by lwjohnst86** [comment]
@philter87 completely agree that when I think of "table", I think of that table! But the connection between a table like that (found in papers and reports) and a "table" as a CSV file/spreadsheet/rectangular data format isn't as clear/obvious.

**Comment by philter87** [comment]
I can't fully envision the "consequences" of renaming to "data", but we can give it a try. 

First of what is the replacement of these ("create table" vs "add data to existing table"): 
![image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/b0b60fb8-27c7-4808-9ee5-da5de3e59bb7)

And should we align with the names in the code? Or can we use more technical terms in the code?

**Comment by lwjohnst86** [comment]
We definitely should use more technical terms in the code!! I definitely don't think using more vague terms in technical settings is good 🦾 but for the user, keeping it more general and accessible is a better approach I think 😁 

I think the new titles might be "Upload new data" or "Add new data" or even "New data" and "Add to existing data" or "Existing data".

**Comment by philter87** [comment]
Yes, that might be okay with "New data" and "Add to existing data"

**Comment by philter87** [comment]
| TableMetadata  | ColumnMetadata   | ColumnDataType | FileMetadata |
| ----------------- | -------------------- | ------------------- | --------------- |
| Tables                | Columns                | DataTypes             | FileMetadata |
| Schema             | SchemaVariable     | SchemaType         | FileMetadata |
| DataDefinition  | DataVariable          | DataVariableType  | FileMetadata |
|                           |                               |                               |                      |

**Comment by lwjohnst86** [comment]
With the move to frictionless, this isn't as relevant anymore
