### ISSUE TITLE
bug with polars.read_csv. Unable to handle comma within quoted field "Some text, some other text"

### ISSUE THREAD

**Issue by philter87** [seedcase-project/seedcase-sprout#262]
Unable to handle this CSV. Index 6, there is a comma in "Banana Boat Sunscreen, 8 oz" which causes an error
```
"Index", "Item", "Cost", "Tax", "Total"
 1, "Fruit of the Loom Girl's Socks",  7.97, 0.60,  8.57
 2, "Rawlings Little League Baseball", 2.97, 0.22,  3.19
 3, "Secret Antiperspirant",           1.29, 0.10,  1.39
 4, "Deadpool DVD",                   14.96, 1.12, 16.08
 5, "Maxwell House Coffee 28 oz",      7.28, 0.55,  7.83
 6, "Banana Boat Sunscreen, 8 oz",     6.68, 0.50,  7.18
 7, "Wrench Set, 18 pieces",          10.00, 0.75, 10.75
 8, "M and M, 42 oz",                  8.98, 0.67,  9.65
 9, "Bertoli Alfredo Sauce",           2.12, 0.16,  2.28
10, "Large Paperclips, 10 boxes",      6.19, 0.46,  6.65
```

It seems tricky to solve... Should I revert back to using default python csv reader for transforming the file? 

We could also read a line at the time and then do weird regular expressions to fix the file, but it seems a bit too much

**Comment by lwjohnst86** [comment]
Mmm, I feel like this might be a bug with polars then. Could you open a bug report with them? This is a pretty standard thing to do when reading a CSV file, since the string is quoted.

**Comment by lwjohnst86** [comment]
We could include a "csv sanitizer" before reading in. The polar's issue on this references tools like [qsv](https://github.com/jqnatividad/qsv) and [xsv](https://github.com/BurntSushi/xsv), but they are both Rust tools. Couldn't easily find a Python CSV sanitizer though.

**Comment by philter87** [comment]
I have added a bug report: https://github.com/pola-rs/polars/issues/15011. But maybe they do not want to fix it because whitespace according to the very old csv spec should be considered part of the string

**Comment by philter87** [comment]
They responded to the issue, and they don't see it as an issue, so.... what to do now?

**Comment by lwjohnst86** [comment]
Hmm, I think maybe for now we assume the CSV is formatted correctly (i.e. no leading whitespace between comma separators). And if it becomes an issue we look into using the duckdb approach they mentioned in the issue.

For instance, if we remove the leading whitespace in the example you gave, it works as intended.

```
import polars

csv_content = """
"Index","Item","Cost","Tax","Total"
 6,"Banana Boat Sunscreen, 8 oz",6.68,0.50,7.18
 7,"Wrench Set, 18 pieces",10.00,0.75,10.75
 8,"M and M, 42 oz",8.98,0.67,9.65
 9,"Bertoli Alfredo Sauce",2.12,0.16,2.28
10,"Large Paperclips, 10 boxes",6.19,0.46,6.65
"""

with open("temp.csv", "w") as csv_file:
    csv_file.write(csv_content)

df = polars.read_csv("temp.csv")

print(df)
```

**Comment by philter87** [comment]
Deal! Lets do that
