### ISSUE TITLE
Discussion: Where to save helper functions?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#263]
We started a small discussion about this when @signekb created the `convert_to_snake_case()` function. I think it might make things easier for us when developing to place helper type functions in a common location. What's commonly done in Python @philter87? Create a new folder called `helpers/` and store individual functions in files there?

**Comment by philter87** [comment]
Yes, I think a "helpers" folder is great idea - potentially with subfolders as I have needed a place to put the CSV parsing stuff. 

I think the "Django-way" is to add methods on the model objects, but I don't always think that makes sense.

**Comment by lwjohnst86** [comment]
We've discussed this a bit over a few meetings and PRs, and I think we'll see how things progress and move things into folders based on patterns of files that we have. Closing.

**Comment by lwjohnst86** [comment]
An idea I had. What if we use a file name as an action e.g. `verify.py`, and the functions inside as the objects e.g. `is_dir()`. Then when we import we do:

```
import verify

verify.is_file()
```

Thoughts?

**Comment by K-Beicher** [comment]
Seems like a sensible thing to do.

**Comment by signekb** [comment]
As I said during an update meeting, I'm onboard with this idea - as long as the scripts don't get too long (+500 lines). I think we should try it out :)

**Comment by signekb** [comment]
Currently, we tend to include specific functions with `from x import y`, in which case - if we continue to do so - we'll lose the verb. This, ofc, would make the what the functions do less transparent. But, I guess we can just start to import entire modules instead, like `import verify` or `import create`? 

Examples:

```python 
# not clear what actions the functions complete bc we lose the verb
from create import next_id, readme_text

next_id()

readme_text()
```

```python 
# still clear what they do
import create

create.next_id()

create.readme_text()
```

**Comment by lwjohnst86** [comment]
Made some issue related to this discussion, closing.
