### ISSUE TITLE
[feature-request]: Allow editing of table name and description in metadata edit page

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#266]
### What feature would you like to request?

Right now there is no way for the user to edit these fields, for the metadata on the table itself. Not sure if it's a good idea to edit the table name itself though. Thoughts? Allow editing of description by any authorized user but only edits to the table name by admin?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by K-Beicher** [comment]
I think we need to look at the option of having a role that the admin can assign to people which will allow them to help with the editing of metadata, that way the description fields won't be available for all to update, but at the same time isn't the sole responsibility of the project owner'/main admin.

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
