### ISSUE TITLE
Column-review. Suggestion for illustrating column metadata

### ISSUE THREAD

**Issue by philter87** [seedcase-project/seedcase-sprout#270]
This address two problems: 
1. User experiments show that people find it a bit confusing that column metadata is displayed as rows. 
2. @lwjohnst86 wanted to show preview data (how does the data look after inferred types)

Based on @K-Beicher's work, I have styled two suggestions

## 1# Suggestion
![Image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/8618c0f5-54f4-4316-8fd6-0bd6d9584a22)

When the edit button is clicked for one of the columns, then a dialog opens:
![Image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/30921927-0395-4c04-bea6-2b316e003ddc)

Problems:
1. We will need to add horizontal scrolling, when several columns are added
5. It requires more clicks to fill description. We might help the user a bit by adding a button "Next column" in the dialog

## 2# Suggestion
![image](https://github.com/seedcase-project/seedcase-sprout/assets/5868902/b71a626d-d725-46ef-bb0c-05c8aae81e7b)

**Comment by lwjohnst86** [comment]
Hmm, I really like that "grid table" style! Instead of scrolling horiztonally, what about having a responsive grid table style, like 4 items per row of a grid? Like in your suggestion #2?

**Comment by philter87** [comment]
Yes, that is a great idea and I would love to play more with it, but I wanted to make sure that it is the correct path?

**Comment by philter87** [comment]
@lwjohnst86 #2 is not updated where the columns go to the next line

**Comment by lwjohnst86** [comment]
Which issue are you referring to? #2 is about login and authentication.

**Comment by K-Beicher** [comment]
I believe #2 here is talking about the second option, not the issue?

**Comment by philter87** [comment]
Yes, I meant the second suggestion :) But I also found pretty confusing spelling error in my comment which is corrected ('**not**' should have been '**now**'). The second suggestion is **now** updated, with your proposal.
