### ISSUE TITLE
Discussion: Which fields to include to edit in metadata creation (vs editing?)

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#288]
> We probably need a discussion of which fields we want to offer the user to edit after the first creation of the metadata, and which we will allow them to edit when they are setting up the metadata.  
> 
> My suggestion would be that all fields are shown to the user at creation (so adding a field to the view in this PR) with only Original Name locked down. Once the metadata has been stored in the database only Display Name and Description are editable (in which case we should remove either Original Name or Title from the file as it stands here). 

@seedcase-project/developers

_Originally posted by @K-Beicher in https://github.com/seedcase-project/seedcase-sprout/issues/273#issuecomment-1999368568_

**Comment by philter87** [comment]
Yes, I think we should not scare the user with too much information. 

Arisa was confused with just two names and since we have added a third.

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
