### ISSUE TITLE
[user-story]: Schema Creation and Data Upload - one or multiple files?

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#29]
### What user story would you like to add?

As a Data Contributor, I want to be able to upload multiple files at once, so that the uploading process will be easier. 

Discussion from user flow PR #27 
- @signekb: Data vs file: File indicates only a single file (e.g., csv) can be uploaded at a time. Is that what we want?
- @lwjohnst86: Good question... I don't see why we couldn't upload multiple files that are each scanned and create multiple schemas from them. Maybe for now we assume multiple (without explicitly saying it here?).
- @K-Beicher [commented](https://github.com/seedcase-project/seedcase-sprout/pull/27#discussion_r1430055578): I don't think I've ever seen a system which allowed for multiple files to be uploaded at the same time if they require the level of validation that we suggest will take place. Also, can you imagine the hassle of attaching several files just to have to do it again because one of them failed. We may want to add this as a discussion item to one of our meetings.

@signekb: Maybe Sprout could allow the submission of one schema at a time and then multiple files following the same schema at a time? This would allow a Data Contributor to upload multiple csvs at a time (e.g., if they have one csv per patient per visit with the same measurements/that follows the same structure/schema)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by signekb** [comment]
@lwjohnst86 @K-Beicher @philter87 I have updated the description of this issue. What are your thoughts?

**Comment by signekb** [comment]
Amazing. I'll leave this open for now, and wait for @K-Beicher's comments, before I close it.

**Comment by K-Beicher** [comment]
Still not sure that people will want to use this, but I may be limiting my thinking to files that are prone to errors, where it would be a pain in the... to select multiple files if one of them then fails.  I can see it would be convenient if you know that the data is perfect.

I think it is a low priority development though.

**Comment by signekb** [comment]
@K-Beicher That's a good point. I'm thinking of a scenario where you have one file per participant e.g., in an experiment and you know that the data is similar in those files. But I agree, this is low priority. 

Maybe we should even just close this for now and return to it if it becomes relevant again?

**Comment by lwjohnst86** [comment]
@signekb I'm in agreement with you too, there are definitely situations where the data is literally the same structure/format because it's output by a machine (or a very explicit protocol followed by people) that would be nice to be able to upload multiple at a time. Let's not close it but return to it at another point.

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
