### ISSUE TITLE
Discussion: Naming practices of Python files

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#296]
How do we want to do this? A file for each function within? Generic action name, with functions for actions on objects within?

**Comment by lwjohnst86** [comment]
I think with the current refactor work/changes to using core, this issue has basically be incorporated. Closing.

**Comment by signekb** [comment]
@lwjohnst86 Both yes and no, I guess. This is how we name python *files*, right?
