### ISSUE TITLE
Discussion: What to do with uploads with 100+ columns in terms of editing

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/seedcase-sprout#301]

**Comment by K-Beicher** [comment]
It is the idea that we can encounter data sets with many columns, for instance genomics data.

When such a data set is initially uploaded and presented to the user, the field Description will be blank, and will need to be completed by the user, prior to upload of the data.  This will be a labour intensive job, and it would be beneficial if the user could complete this over several sessions (otherwise the risk of all descriptions being TBC, is high).

At present the page for editing the initial upload doesn't allow for any fields to be left blank, as django won't allow a form to be submitted with missing data. 

I see two solutions.  1/ we force the user to complete all fields (with the risk mentioned above), or 2/ we allow for the form to save with the Description field left blank (but don't allow for data upload until it is completed).

@seedcase-project/developers anyone see any other options?

**Comment by K-Beicher** [comment]
Good point, I'm also thinking of those users who start filling it out, and then get called away halfway through.  They won't be all that happy if they've already completed half of the data and then aren't allowed to save it.

Is it possible to run a check on completeness of data on the overview page which will allow them to either upload or edit a schema?  That way we could stop them from uploading until they have completed the descriptions.

**Comment by philter87** [comment]
@K-Beicher I think I like the idea about allowing blank descriptions and then not allowing data upload. 

Downloading, editing and uploading metadata sounds a bit awkward for the user (and might also be quite hard to implement correctly)

**Comment by lwjohnst86** [comment]
@philter87 I think having the ability to download the metadata is an important thing. People (unfortunately) like spreadsheets, so giving an option to download it, if nothing else but to do things to the metadata in Excel etc however they might like to.

But, I agree with you, it might be a bit awkward and won't be high priority for now.

What about requiring the metadata before the upload data option can be clickable/available? And "updating table" as they go, to return to it later through `project id metadata id update`?

**Comment by philter87** [comment]
Yes, I like that they can do it later. 

We can maybe also introduce warnings, so we nudge them to add descriptions but we don't force them

**Comment by lwjohnst86** [comment]
We discussed this and agreed to create a page dedicated to saving/creating metadata `project id metadata create`.

**Comment by signekb** [comment]
@lwjohnst86 Should I create an issue on this?
