### ISSUE TITLE
[feature-request]: Add Ruff linting/formatting to justfile 

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#31]
### What feature would you like to request?

To lint/format right away, add Ruff to justfile

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by signekb** [comment]
@lwjohnst86 From doing some initial research, it seems that for VS Code, the [Ruff VS Code extension](https://github.com/astral-sh/ruff-vscode) is recommended. Should we just include Ruff in the extensions.json instead of adding it to the justfile?

**Comment by lwjohnst86** [comment]
I would do both, since others like Philip don't use vscode 😊

**Comment by signekb** [comment]
Makes sense. Will do both 👍 We could also add the `ruff-action` to run on prs as described in [this post](https://dev.to/ken_mwaura1/automate-python-linting-and-code-style-enforcement-with-ruff-and-github-actions-2kk1)?
