### ISSUE TITLE
Wireframes: Alternative flow for Sprout

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#315]
Including review/feedback with @henrik-goul

**Comment by signekb** [comment]
@seedcase-project/developers I had a meeting with @henrik-goul today about the alternative flow of Sprout. I have now added it to the wireframes in Figma. Will you take a look at it, i.e., review it?

**Comment by K-Beicher** [comment]
I like those, left a few comments on it, but overall it's looking good.

**Comment by philter87** [comment]
I like your alternative flow - there are many aspects in it. Maybe we discuss the flow in a meeting as well?

**Comment by signekb** [comment]
Glad to hear that @philter87. Yes, that's a good idea. If you have any comments and/or considerations, please add it as comments in the wireframes :)

**Comment by signekb** [comment]
@seedcase-project/developers I have replied to your comments in Figma. When you have time for it, please go take a look and reply in there :)

**Comment by signekb** [comment]
This has been reviewed in Figma - and a new flow for creating metadata has been proposed in #397.
