### ISSUE TITLE
Discussion: Which Python docstring format/standard to use?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#33]
Seems there are a few to use. Google, PEP, Numpy Standard, etc. Which is good to use for us?

**Comment by signekb** [comment]
I am used to Google-style, so I guess I have a preference for how that looks. 
However, one annoying this about that is that bc you both define the parameter type in the function definition and describe it in the docstring, you have to remember to change it both places whenever you change the type. It seems to be the same with Numpy-style. I'm not sure how often we'll change types, but we tended to do it a lot during my thesis, and it was quite annoying. 

**VS Code Extension for Docstrings** 
I have used the [autoDocstring](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) extension for VS Code, which I believe defaults to Google. It can be used for the other standards as well, so it could be a nice extension to add to our recommendations, once we decide on which docstring convention to use. 

With this extension I think it's pretty easy to use either style, so I'm open to try either :)

**Comment by philter87** [comment]
I am no expert, but I think google docstrings looks the best

**Comment by lwjohnst86** [comment]
I think I'm in agreement, Google style docstrings look better too. Closing and will create a decision post about it.
