### ISSUE TITLE
Move table name and description creation into `projects-id-metadata-create`

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#341]
Right now the table names and descriptions are created in the `project-id-view.html` as a dialog box. I think it makes more sense to have that creation in the `project id metadata create`. It would simplify things, like not needing to pass around the table metadata object and it would make it so the create URL is more consistent with our naming scheme. Right now, the URL is `project id metadata id create` which feels a bit inconsistent, since in order to have an id, we need to create it first, but in this case we have an id as we're creating it...

**Comment by signekb** [comment]
This is on hold until the team has agreed on the design, see issue #397

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
