### ISSUE TITLE
[bug]: When there's more columns than headers in the uploaded csv, the added metadata aren't saved

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#391]
### Steps to reproduce

1. Click "Create New Metadata" > Enter random name and description > Click "Create"
2. Upload [patients.csv](https://github.com/seedcase-project/seedcase-sprout/files/14976330/patients.csv) on the next page to create the metadata from > Click "Extract Data Structure"
3. The next page will look as follows:  
![Screenshot 2024-04-15 at 10 46 02](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/0bc2fde6-afee-4ebc-b2b7-c3613e0833d6)
- See the last card with the missing header 
4. Add descriptions and the "Display Name" for the last card > Click "Update All"

5. Then go back to the homepage and click "Add to Existing Metadata" 
6. Click on the metadata you just created. It looks as follows: 
![image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/bb762275-56ff-4a4f-813d-d1bca655d0df)

### Expected result

1. I'm not sure that I, at the current stage of `sprout`, should be able to create metadata without an `extracted_name`? 
2. When examining the metadata, the fields that I have filled in, `description` and `display name` for the last column, should be populated with the values I added.

### Actual result (the bug)

1. I am able to create metadata for a column without a header in the uploaded file 
2. The metadata I provided (i.e., descriptions and display name of the column without a header) is gone

### Severity/Priority

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
