### ISSUE TITLE
Design a unified `projects id metadata create` page where *all* metadata is created

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#397]
After a discussion at the update meeting Thursday 18 April, @lwjohnst86 proposed that we include **all** metadata creation (i.e., both what we internally call "table" metadata and "column metadata") on **one** page. This would fit the naming scheme a lot better if we only have one page `project id metadata create` for metadata creation.

Based on that talk, I have created a new version of the "create metadata flow" in the green area in the Wireframes tab in Figma. 
@seedcase-project/developers  Please go have a look at it and add comments/questions/suggestions for improvements to it :) 

PS I got some help from my UX friend (shout out to her 🥳 ) to come up with this "toggle" layout.

**Comment by signekb** [comment]
@henrik-goul @seedcase-project/developers I have updated the newest flow based on my meeting with Henrik today. Please take a look and add comments 👍

**Comment by K-Beicher** [comment]
I do like it!

**Comment by lwjohnst86** [comment]
Done!!
