### ISSUE TITLE
Wireframe for "shopping cart"

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#421]

**Comment by henrik-goul** [comment]
I have now created a rough draft for how people can browse data projects, see some their titles, descriptions and data owner (+ a few extra things) and apply for access:
https://www.figma.com/file/czeKwMxVLKPNQDX42eiTxq/Wireframes?type=design&node-id=1442%3A2714&mode=design&t=OhyfBczggirDsItk-1

For now the design only accounts for users applying for all available data within a project, and does not allow the users to browse and apply for each column of data, as was originally discussed during our eventstorm workshop. I know this might be a requirement, but I was not sure if it was to be part of a first iteration. So for now I kept it as simple as I could.

Whenever someone has requested access, their application would then need to be reviewed and approved on the "Requests" screen in the "User Management" section in the wireframes :)

I hope it all makes sense! If you have any questions, do not hesitate to shoot me an email, as I will be turn off notications for this github projects today.

It was a pleasure to work with you all, and I hope you get the chance again in the future @lwjohnst86 @signekb @K-Beicher ! :)

All the best,
Henrik
