### ISSUE TITLE
Discussion: Any usefulness of building Django project as a package as well?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#46]
It's possible to build Django projects as reusable apps (https://docs.djangoproject.com/en/5.0/intro/reusable-apps/). Means we can also publish it on the Django Packages site: https://djangopackages.org/ or on PyPI (via `pipx`). It seems like it would be a good approach to do considering we will combine projects together into a single "seedcase" app. But I'm not sure, I don't know Django enough to know if this is a useful approach or not. Thoughts?

**Comment by signekb** [comment]
At Feb 12, we decided to leave this issue in the backlog for now.

**Comment by lwjohnst86** [comment]
We're already doing this now, closing.
