### ISSUE TITLE
Investigate and review code and create issues for refactoring

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#475]
For instance, look for places where the input/output isn't consistent or changes based on a condition. Or when a function is doing too much (except for larger user-facing functions). Or when a function has too much code that could be split out more into smaller more composable functions. 

The easier and simpler a function is that doesn't depend on too many other things, the easier it is to test. This follows the SOLID principles of software engineering: https://en.wikipedia.org/wiki/SOLID. It also follows functional programming.

**Comment by martonvago** [comment]
List of issues with a focus on `sprout`:
- https://github.com/seedcase-project/seedcase-sprout/issues/504
- https://github.com/seedcase-project/seedcase-sprout/issues/512
- https://github.com/seedcase-project/seedcase-sprout/issues/514
- https://github.com/seedcase-project/seedcase-sprout/issues/515
- https://github.com/seedcase-project/seedcase-sprout/issues/508
- https://github.com/seedcase-project/seedcase-sprout/issues/509
- https://github.com/seedcase-project/seedcase-sprout/issues/510
- https://github.com/seedcase-project/seedcase-sprout/issues/513
- https://github.com/seedcase-project/seedcase-sprout/issues/511
- https://github.com/seedcase-project/seedcase-sprout/issues/516

**Comment by lwjohnst86** [comment]
Great! So we can close this one now 😁
