### ISSUE TITLE
[feature-request]: Add pop-up with metadata instead of dropdown 

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#477]
### What feature would you like to request?

A part of this #388 was to examine metadata with a pop-up instead of a dropdown menu. It would be nice to implement the pop-up since it will allow us to use `<table>` instead of `<div>` on that page as well.

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
