### ISSUE TITLE
Investigate how to mix Django with a CLI

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#480]

**Comment by lwjohnst86** [comment]
There is a lot of overlap with what @martonvago has done in #479.

**Comment by signekb** [comment]
Stumbled upon [Typer](https://typer.tiangolo.com/) that builds on top of [click](https://click.palletsprojects.com/en/8.1.x/). Not sure we need it, but just wanted to write it down

**Comment by lwjohnst86** [comment]
I think with the redesign and work by @martonvago (and things I am writing down/will eventually write down) this issue has been incorporated into our plans. Closing.
