### ISSUE TITLE
Transform a small bit of code into a prototype of what we discussed

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#484]

**Comment by martonvago** [comment]
[Here](https://github.com/martonvago/smiling_panda)'s an (emphatically) explorative first pass at creating an app with separate components for the command-line interface, the web interface and the core logic.

**Comment by martonvago** [comment]
The one thing that I think would be a useful addition here is adding the commands as entry points to the app and implementing a better strategy for setting up Django before CLI commands are executed.

**Comment by lwjohnst86** [comment]
Very nice, thanks for the example 🤩 I'm not sure I understand your comment about entry points and the app. I understand entrypoints as things Python provides as accessible to the OS when installing the package, but how does that connect to the app? Wouldn't we use the `import sprout.core.module` pattern when building the Django app?

**Comment by martonvago** [comment]
Sorry, I think I used "app" very loosely to mean the package we install. (And I added the CLI commands as entry points anyway, so that's not even relevant.)

**Comment by lwjohnst86** [comment]
This helped inform on #479, closing now 🤩
