### ISSUE TITLE
[discussion]: How do people use similar terms compared to the frictionless standard

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#495]
### What would you like to discuss?

As described here: https://datapackage.org/

A data resource for them is a single file/table, while a data package is a collection of data files/tables and associated metadata. Maybe we should align on these terms? And how do others use them (e.g. NNF and "Data Resource")?

**Comment by signekb** [comment]
I thought the same, when I looked at their documentation 👍

**Comment by K-Beicher** [comment]
There doesn't seem to be a standard for all this, funders and other IT professionals are all over the place in terms of shared terminology, so we have decided that we will go with Frictionless/
