### ISSUE TITLE
Investigate how Sprout will be deployed as demo version

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#5]
# Infrastructure of Sprout demo
- How will it be installed? 
- How will it be deployed on the installed server? 
- How will it be bundled? 

Currently, the plan for production is to run sprout application on a server owned by Aarhus University. This is not optimal, but it seems to be a legal requirement. Deploying to such a server will be complicated, so we also want a demo/preview environment in the cloud. There are several options available and I have created a matrix describing the different features depending on the cloud service.

We would like the demo/preview environment to look similar to the production environment (Aarhus University Server). The problem is we don't know any details about the production environment, but maybe we can assume that docker will be available.

|                                                                 | Azure          | Render                       | Digital Ocean            | Vercel                    |
| --------------------------------------------------------------- |:--------------:| ----------------------------:| ------------------------ | ------------------------- |
| Price (per month)                                               | 1000kr         | Free or<br>19$/user + 20$/DB | ?                        | Free or<br>20$/user       |
| Complexity                                                      | High           | Medium                       | ?                        | Low                       |
| Customizability (Poetry)                                        | High           | Medium                       | ?                        | Low                       |
| GitHub Auth                                                     | No             | Yes                          | Yes                      | Yes                       |
| Github Actions Integration                                      | Very good      | Sort of (deploy webhook)     | Yes                      | Yes                       |
| Managed Postgres                                                | Yes            | Yes                          | Yes                      | Yes                       |
| File Storage service                                            | Yes            | Yes (FTP) 0.25$/GB           |                          |                           |
| "Native support for Django app"                                 | Sort of        | Yes<br>(Poetry support)      | ?                        | Yes<br>(requirements.txt) |
| Docker Image or DockerFile support                              | Yes            | Yes                          | Yes                      | No                        |
| Docker-compose                                                  | Yes            | No                           | Yes (with a normal node) | No                        |
| Logging                                                         | Very good logs | Simple                       | Simple                   | Simple                    |
| Alert                                                           | Yes            | No                           | ?                        | No                        |
| Similar to production environment<br>(Aarhus University server) | Likely possible        | Maybe if docker on university server                          | Likely                   | No                        |

So what is the conclusion? 

**Render.com**

Render seems to be the best choice at the moment for these reasons
**Pros**
- It is free (if only one user needs to access render)
- It is simple to setup, but still easy to configure after our needs. For instance, it works well with poetry
- It supports Docker images and also Dockerfiles (no need for a place to store docker images)
- Luke likes the simple aesthetics of the render.com admin page 😃  

**Cons**
- It lacks certain capabilities when it comes to logging and alerting, but this is less relevant because it will mostly be used as a demo environment
- It does not resemble a University server, but that is hard to prepare for anyways
- There is no support for docker compose, which could be nice but we don't know yet if this is relevant

**Comment by lwjohnst86** [comment]
Closed by https://github.com/seedcase-project/design/pull/2
