### ISSUE TITLE
Prefer singular variable and property names for single objects

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/seedcase-sprout#508]
Maybe a personal preference, but I find the plural for the model names a bit confusing. It seems to lead to naming variables in the plural (e.g. `tables = Tables.objects.get(pk=table_id)`) which actually refer to singular instances. Similarly, within models some properties use a plural name while actually pointing to a single object in a many-to-one relationship (e.g. one `File(s)` belongs to one `Table(s)`, but this table is accessed through the `tables` property).

**Comment by lwjohnst86** [comment]
We have the style guide say exactly what you describe: https://design.seedcase-project.org/style/naming#variables

So if it only contains one table, it should be called `table`. 💪🏻 So not just a personal preference 😁
