### ISSUE TITLE
Tidy up template variables

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/seedcase-sprout#514]
- Variables should be passed to templates through `context`. E.g. in `projects-id-metadata-create.html` we access `request.GET.step` directly. I'm just thinking that this pattern cannot be mirrored in the command-line interface and it also makes the dependencies of / input to templates more opaque, so we might as well avoid it.
- We should only pass variables to a template (through `context`) that are actually used in that template. E.g. in `render_projects_id_metadata_create` we pass `table_name` to `context`, but I wasn’t able to find where it is used in the corresponding template.

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
