### ISSUE TITLE
Organise (meta)data into data projects

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/seedcase-sprout#531]
Based on our discussions and documentation in the code, in Sprout (meta)data are grouped into projects.

We should update the code to reflect this organisation.

One example:
In `sprout/app/views/projects_id_metadata_view.py` we say we want to "view the existing metadata in a project", but then fetch all metadata/tables regardless of the project.

**Comment by lwjohnst86** [comment]
Won't be relevant after refactoring app to use core.
