### ISSUE TITLE
Update `create-resource-structure` diagram

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/seedcase-sprout#569]
We should eventually update this [diagram](https://github.com/seedcase-project/seedcase-sprout/blob/main/docs/design/images/core-python-functions/create-resource-structure.svg) to reflect the final implementation of the `create-resource-structure` function.

See #568 for the final implementation and links to the inner functions.

**Comment by signekb** [comment]
@martonvago I have made a minor change already in this PR: https://github.com/seedcase-project/seedcase-sprout/pull/584

**Comment by martonvago** [comment]
@signekb, ah cool, turns out I've also included that change on this one
