### ISSUE TITLE
Test helpers for working with files and folders

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/seedcase-sprout#570]
Have a think about whether there are any useful common functions for testing that would help us to set up (and tear down) folder structures quickly when we run tests against them.

This is probably best done after we've written a couple of tests and see what our needs actually are.

**Comment by lwjohnst86** [comment]
Make use of temporary paths with tempfile module: `tempfile.TemporaryFile()` etc

**Comment by lwjohnst86** [comment]
Not sure if this is relevant anymore?

**Comment by signekb** [comment]
I guess this comes up naturally as we create tests? For example, I added some helpers for testing the `path_*()` functions in #730 
As we go, we can keep in mind how we want to structure these helper functions and fixtures?

**Comment by lwjohnst86** [comment]
I think we have some good functions already to help with this.
