### ISSUE TITLE
Runtime view: Move relevant sections on data input and data flow and agree on them

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#6]
https://github.com/seedcase-project/seedcase-project/blob/66213743aae1a71186a1b7147826407f85f09945/design/software-architecture/runtime-view.qmd#L18-L169

Also add C4 dynamic diagrams

**Comment by K-Beicher** [comment]
@lwjohnst86 I'm right in thinking that we only want to move over the parts of this that are relevant for Sprout, so leave behind the stuff about manual entry etc.?

**Comment by signekb** [comment]
Hmmm, wouldn't that be a part of Sprout eventually?
