### ISSUE TITLE
Create and test `edit_property_field()` - a part of `create_properties_template()`

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#623]
Signature: `edit_property_field(properties: json, field: str, value: str) -> json:`

Arguments:
- `properties`: json with properties
- `field`: string with field to edit
- `value`: string with value to add to the field

Returns: json with properties with a field edited

Context: see the `create_properties_template` [diagram](https://github.com/seedcase-project/seedcase-sprout/blob/main/docs/design/images/core-python-functions/create-properties-template.svg) 

This function edits the field values to the defaults we use. 

@signekb: I'm guessing we'll use this several times and might include a `edit_property_fields()` function - like with `create_dir()`and `create_dirs()`. What say you, @lwjohnst86 ?

**Comment by martonvago** [comment]
Is this basically the same thing as https://github.com/seedcase-project/seedcase-sprout/issues/576 ? If so, we could rename `edit_resource_properties_field` > `edit_property_field` or `edit_properties_field`.

**Comment by signekb** [comment]
@lwjohnst86 ?
