### ISSUE TITLE
Create dataclasses representing the top levels of the data package spec

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#625]
Create dataclasses to represent the top levels of the [data package spec](https://datapackage.org/profiles/2.0/datapackage.json), including most* package and resource properties, but excluding `resource > schema` and everything under there. 

\* which ones we want to include is a work in progress

Dataclasses:
- PackageProperties
- ResourceProperties
- SourceProperties
- LicenseProperties
- ContributorProperties

We want to be able to instantiate the classes with no arguments, so provide sensible default values.

Ideally, the classes should be generated automatically based on the data package spec.

**Comment by signekb** [comment]
Ah, I think you're right! It does need some rearranging to be used as a template. In my mind it would also be easier to construct a template file by hand instead of creating specific logic to rearrange the json at the url. Even though it would be nice if it could rely on the spec directly. What do you think, @lwjohnst86 ?

**Comment by martonvago** [comment]
Or another thought would be to see if there's a library that can generate a sample json object based on a json schema? And then we could just drop fields we don't need. I looked very quickly but no immediate clear hits.

**Comment by martonvago** [comment]
Well, it doesn't seem that hard to do, so I'm having a look at it today^^
