### ISSUE TITLE
Design and finalize data import page

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#70]

**Comment by henrik-goul** [comment]
The wireframes for data import is ready for a final review, and as agreed during our status talk I will tag you all in here and leave a link to 
@philter87 @signekb @lwjohnst86 @K-Beicher 

Figma:
https://www.figma.com/file/czeKwMxVLKPNQDX42eiTxq/Wireframes?type=design&node-id=0%3A1&mode=design&t=ymjeUcfnmaQ81NNx-1

**Comment by signekb** [comment]
Looks good! I have currently added a "Cancel" button in the overlay as well. 
![image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/13e62402-d6b0-47c8-8214-bc9a40d5ea80)

**Comment by philter87** [comment]
Looks good!

**Comment by lwjohnst86** [comment]
Finally had a chance to review things. Looks great! Only comment I might have is, how common is it to include a "back" button?

**Comment by henrik-goul** [comment]
@lwjohnst86 Good comment, I have added a back button now as well ;)
