### ISSUE TITLE
Design and finalize page that lets us view and edit extracted metadata columns and types

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#71]

**Comment by henrik-goul** [comment]
@lwjohnst86 @signekb @K-Beicher @philter87 I would like some input on the users' ability to add extra columns in the metadata table.
- Is this a feature we want to include in the first iteration?
- Is the added column a simple column to contain varchar, or should the user be able to define the content and rules for the content somehow?

**Comment by K-Beicher** [comment]
I'm not entirely sure what you mean, I wouldn't expect a user to be able to add columns to the tables containing metadata, those should be defined by us (and maintained by us.  Of course they won't be static forever and ever, but it would be a major change if those tables were to change.  They should be able to add all the rows they want (they are the ones that define their own tables, the ones containing research data), and that is what we are thinking of here. 

Does that make sense?

**Comment by henrik-goul** [comment]
@signekb thanks for adding context Signe, that is exactly the comment I was referring to :)
We can definitely add such a feature from a user interface perspective, but is it needed at this time?

And maybe I have been confusing you all a lot. When @signekb mentions the ability to add a COLUMN, I was assuming it was a column to the right of "Allow Duplication" in the screen above in Signes comment, But I suppose what your comment is suggesting @signekb, is the ability to add a row below "Weight" in the screen above, as the rows here represent columns in the table created. Sorry if that is confusing!

**Comment by signekb** [comment]
I think you're right, @henrik-goul. It might not be necessary at this point

**Comment by henrik-goul** [comment]
The wireframes for data import is ready for a final review, and as agreed during our status talk I will tag you all in here and leave a link to 
@philter87 @signekb @lwjohnst86 @K-Beicher 

Figma:
https://www.figma.com/file/czeKwMxVLKPNQDX42eiTxq/Wireframes?type=design&node-id=0%3A1&mode=design&t=ymjeUcfnmaQ81NNx-1

**Comment by signekb** [comment]
Nice! I like the dropdown menu and the added colour to the boolean fields when "Yes" is chosen. 
@henrik-goul Is the "Advanced features" button just leading to nowhere at the moment? And will we keep it like that for now?

**Comment by henrik-goul** [comment]
@signekb the "advanced features" lead to this screen, which I had forgot to name appropriately:


![Image](https://github.com/seedcase-project/seedcase-sprout/assets/152619915/7895051c-5fa7-4141-8f99-04b5882bdc21)

**Comment by signekb** [comment]
@henrik-goul Ahh!I didn't get that from the wireframes. Thank for explaining!

**Comment by lwjohnst86** [comment]
Looking great 🤩 Not super convinced of the usefulness of the "length" and "precision" columns. But I do like the idea of an "advanced section" for things we can add on to later. Keep it basic as default, but give the option for a bit more.

**Comment by lwjohnst86** [comment]
Only other thing I thought of is, what if the person needs to come back to it later? Or to save the progress or something? I guess that will come with adding log-in features.

**Comment by henrik-goul** [comment]
@lwjohnst86 I am glad you like the "advanced section", I was trying to design something flexible for the future so I am glad that shines through :)
For the "length" and "precision" columns, I believe we can leave them in the wireframes for now if they become relevant later, but if you believe they are not needed in the first development iteration we should let @signekb and @philter87 know :)

**Comment by signekb** [comment]
I think it's a good point to leave precision and length our for now :) I'm also not sure about the usefulness of those. Maybe @K-Beicher has input on this?

**Comment by henrik-goul** [comment]
I'll let this task stay open for @K-Beicher to comment on precision and length and their usefulness :)
