### ISSUE TITLE
Create and test `read_properties()` - a part of `edit_package_properties()`

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#711]
Signature: `read_properties(path: Path) -> json/dict:`

Returns: 
- json/dict with properties

~Should also verify that the properties it loads are valid (see [discussion](https://github.com/seedcase-project/seedcase-sprout/pull/664#discussion_r1745034511)).~ No verifying here, just reading. Since this is an internal only function, we can keep it to only have one action: reading.

Context: See diagram in the [Core Python functions](https://sprout.seedcase-project.org/docs/design/implementation/python-functions) post.

**Comment by martonvago** [comment]
@lwjohnst86 I'm just wondering about verifying the properties loaded from `datapackage.json`: do we want to use the same function/logic as for the `properties` argument in `edit_package_properties`? This would make sense, except that a newly created `datapackage.json` will presumably not have all required fields (well, it will have them set to `null`), so it will be invalid in that sense.

**Comment by lwjohnst86** [comment]
Yea, maybe at this stage, it doesn't validate it, only read it. I'll update the issue description.

**Comment by martonvago** [comment]
But what do we want the behaviour to be if e.g. the contents of `datapackage.json` are not JSON? Exit the entire edit operation or recover somehow (e.g. by using only the values from the `properties` object in the argument to `edit_package_properties`)?

**Comment by martonvago** [comment]
We can close this if we don't want to wrap `read_json` and `verify_properties_are_well_formed` into a separate `read_properties` function.

**Comment by lwjohnst86** [comment]
Agreed, we don't need this function.
