### ISSUE TITLE
Create and test `join_properties()` - a part of `edit_package_properties()`

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#713]
Signature: `join_properties(current_properties: json/dict, new_properties: json/dict) -> json/dict:`

Returns: 
- JSON object with updated properties

Note: New properties overwrite old ones

Context: See diagram in the [Core Python functions](https://sprout.seedcase-project.org/docs/design/implementation/python-functions) post.

**Comment by martonvago** [comment]
@lwjohnst86 Do we actually want any additional behaviour here than what would be achieved by `current_properties.update(new_properties)`? This would add all properties in `new_properties` that are missing in `current_properties`, and for the properties present in both, it would set the value in `new_properties`.

**Comment by lwjohnst86** [comment]
Hmmm, that's a nice function! I'll revise the diagrams to use that instead.
