### ISSUE TITLE
Create and test `edit_package_properties()`

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#715]
Signature: `edit_package_properties(path: Path, properties: json/dict) -> json/dict:`

Context: See diagram in the [Core Python functions](https://sprout.seedcase-project.org/docs/design/implementation/python-functions) post. 

Depends on:

- [x] #711 
- [x] #713 
- [x] #712

**Comment by martonvago** [comment]
@lwjohnst86 Just wondering, if we don't verify the properties coming from the `datapackage.json` in `read_properties`, when should we check that the result of joining the current and new properties is a valid set of properties?

**Comment by martonvago** [comment]
So, basically, we have two checks: the required fields check and the frictionless spec check. We want both for properties derived from `PackageProperties`, but only the spec check for properties loaded from the `datapackage.json`.

So we could have two functions: `verify_package_properties_well_formed` doing the spec check and `verify_package_properties_complete` doing the required check. We can still have a `verify_package_properties` function calling both, as a sort of standard verify function for package properties.

Something like this @lwjohnst86 ?
