### ISSUE TITLE
Investigate and test how to install via pip from GitHub

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#728]

**Comment by signekb** [comment]
Following [this guide](https://www.geeksforgeeks.org/how-to-install-a-python-package-from-a-github-repository/), I "installed" it by simply writing `pip install seedcase_sprout@git+https://github.com/seedcase-project/seedcase-sprout` in a venv. 

I could then run e.g., the following code from the guide in a script: 

```python 
import sprout.core as sp

properties = sp.PackageProperties(
    title="Diabetes and Hypertension Study",
    description="Data from the 2021 study on diabetes and hypertension",
    contributors=[sp.ContributorProperties(
        title="Jamie Jones",
        email="jamie_jones@example.com",
        roles=["creator"]
    )],
    licenses=[sp.LicenseProperties("ODC-BY-1.0")]
)
print(properties)
```

Is this what we want, or is there more to it, @lwjohnst86 ?

**Comment by lwjohnst86** [comment]
@signekb did you run the script in a working directory that wasn't in Sprout? That's great if it was that easy!!!

**Comment by signekb** [comment]
@lwjohnst86 Yes!
I basically just: 
1. Made a new folder (called `test`) on my Desktop
2. Created a venv in it 
3. Ran the command `pip install seedcase_sprout@git+https://github.com/seedcase-project/seedcase-sprout`
4. Made a script `myscript.py` in the `test` folder with the lines from our guide and ran it 👍

**Comment by lwjohnst86** [comment]
Super neat! Well that makes this easy then :grin:

**Comment by K-Beicher** [comment]
So if I can replicate this, I suspect that it will work anywhere. Here is the guide for dummies.

Make a folder `GitTest`
Open a terminal and cd into the folder
Run the command `python3 -m venv testvenv` to create a venv called testvenv
Activate the venv by running `source testvenv/bin/activate`
Create a python script using Signe's script above in the GitTest folder
Run it using the command `python3 mytest.py`
