### ISSUE TITLE
Create an "Installation" document in the Guide section

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#729]

**Comment by K-Beicher** [comment]
@lwjohnst86 is this for the installation of Sprout, or something else/more?

**Comment by lwjohnst86** [comment]
@K-Beicher yes, that's right, for Sprout. It is related to #728 and what @signekb wrote in there.

**Comment by K-Beicher** [comment]
@lwjohnst86 Could you have a quick look at the proposed headings in this branch before I start to write more on them, any of them that are too basic? I've included steps that someone like me a year ago would need to have spelled out in order for the installation to work but maybe that isn't our core audience, and we should skip a few of the points.
