### ISSUE TITLE
Build html file of data import page

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#74]
Build html file of data import page like showed in the wireframe below:

![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/c10dfe35-e7c9-4e90-be33-eb7e93a0abab)

When clicking "Add Data to Existing Table" nothing happens (for now), but when clicking "Create New Table", it should continue to the table description dialogue overlay (issue #75)

**Comment by signekb** [comment]
When we called `table` a `schema`, I asked Henrik to add a (?) that users can hover over to get a description of what it is. 

![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/95201eb1-09b9-4545-8fac-24ce4036ff18)

![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/08e2aab4-94be-4a39-a5a8-e48fdbbcccde)

@lwjohnst86 @K-Beicher Is that still relevant now that we call it a `table`?

**Comment by K-Beicher** [comment]
Not really...  I'm happy to go without a pop-up
