### ISSUE TITLE
Build html "create new table" dialogue overlay for data import page

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#75]
After clicking "Create New Table" (page created with the closing of #74), a dialogue overlay should appear where the user adds table name and description. 

Ensure that we are building the finalised design (check that #70 is closed)

![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/581253ef-026c-4007-a87b-a72da0e9804b)

**Comment by signekb** [comment]
- Dialogue/overlay from beercss: 
```
<dialog>
  <h5>Default</h5>
  <div>Some text here</div>
  <nav class="right-align no-space">
    <button class="transparent link">Cancel</button>
    <button class="transparent link">Confirm</button>
  </nav>
</dialog>
```

- Text field from beercss: 
```
<div class="field label border">
  <input type="text">
  <label>Label</label>
  <span class="helper">Helper text</span>
</div>
```
- Error text field for beercss: 
```
<div class="field label invalid border">
  <input type="text">
  <label>Label</label>
  <span class="error">Error text</span>
</div>
```
