### ISSUE TITLE
Create and test `write_resource_properties`

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/seedcase-sprout#757]
Signature: `write_resource_properties(path: Path, properties: dict) -> Path:`

Context: See diagram in the [Core Python functions](https://sprout.seedcase-project.org/docs/design/implementation/python-functions) post. 

Things to think about:
- is the behaviour of the existing `verify_resource_properties` function exactly what we want here?
- be careful which object exactly (package properties vs resource properties on the package) we're updating when we merge the new resource properties into the old ones

**Comment by martonvago** [comment]
@lwjohnst86 @signekb This should have occurred to me sooner but: a package can have multiple resources, so when we update/edit a resource, we only want that specific resource changed and not the others, right? For new resources we would still want to check that the resource doesn't already exist. 

For this, we would need something unique to identify resources by. Earlier we decided we don't want to save our `resource_id` (i.e. the folder name) onto the resources in `datapackage.json`, so we can't really use that. The spec implies that the `name` field on resources is unique (it makes up foreign key references), so we could use that. Would we be happy with this?

**Comment by martonvago** [comment]
Oh, but we only care about one resource for this iteration. Well, the question still stands I guess 😅

**Comment by lwjohnst86** [comment]
The path field in the resource property contains the resource id 😁 so we can parse that!

**Comment by martonvago** [comment]
Oh trueeeee, I forgot, thanks!!!
