### ISSUE TITLE
fix: 🐛 When creating the first package, the `packages` dir doesn't exist

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#780]
## Description 

I tried to go through the [Create package](https://sprout.seedcase-project.org/docs/guide/packages) guide and found that when I ran `sp.create_package_structure(path=sp.path_packages())`, it fails bc the `path_packages()` directory doesn't exist yet. 

I'm not sure how we want to solve this. We could: 

1. Change the behaviour of all the path functions to also create the dir if it doesn't exist 
2. We could remove the `path` arg from create_package_structure(), and create the dir if it doesn't exist?
3. Other suggestions?

**Comment by lwjohnst86** [comment]
Looking into this more, it looks like only the `path_packages()` needs to create the package dir.

**Comment by signekb** [comment]
Sooo, only change the behaviour of that function is ok?

**Comment by lwjohnst86** [comment]
Yes!
