### ISSUE TITLE
Decide on `seedcase_sprout` as package name or something else

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#782]
It's good practice (and makes things clearer), that the installation name (e.g. `pip install seedcase-sprout`) is the same as the package name (e.g. `import seedcase_sprout`). Right now, it is `seedcase-sprout` for install, but `import sprout` for usage.

**Comment by signekb** [comment]
Maybe `seedcase_sprout` bc `sprout` already exists on [PyPI](https://pypi.org/project/Sprout/)? And hyphens aren't allowed when importing? 
We'll shorten it when we import it anyways so we'll write `import seedcase_sprout.core as sp` instead of `import sprout.core as sp`

**Comment by lwjohnst86** [comment]
You can install with hypen e.g. `https://pypi.org/project/aalink-aarch64/` but import with underscore. Seems to be a recommendation to do `-` for package name and `_` for importing, e.g. https://stackoverflow.com/questions/54597212/using-hyphen-dash-in-python-repository-name-and-package-name

**Comment by K-Beicher** [comment]
The last post in that StackOverflow link talks about not using any of them, and that this has proven to reduce problems, is there anything in that, or is the writer just wearing belt and braces?

No opinion on this otherwise, I don't have enough experience with it.

**Comment by signekb** [comment]
> You can install with hypen e.g. `https://pypi.org/project/aalink-aarch64/` but import with underscore. Seems to be a recommendation to do `-` for package name and `_` for importing, e.g. [stackoverflow.com/questions/54597212/using-hyphen-dash-in-python-repository-name-and-package-name](https://stackoverflow.com/questions/54597212/using-hyphen-dash-in-python-repository-name-and-package-name)

Ah, yes, I have heard of that recommendation. I thought that it might be nice(r)/simpler to just have the same name (i.e., with an underscore: `seedcase_sprout`) for both the package and for importing. But if it's common practice to do `-` and `_` then sure, lets go with that :)

EDIT: 
Just took a look at PyPIs [most downloaded packages](https://pypistats.org/top) and it seems to be common to use `-` for the package name and `_` for import. E.g., `charset-normaliser`, `typing-extensions`, and `grpcio-status`. So, I'm down for doing `seedcase-sprout` for package name and `seedcase_sprout` for import.

**Comment by lwjohnst86** [comment]
Decided :)
