### ISSUE TITLE
Design and finalize page that shows the output of the table extraction

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#79]

**Comment by henrik-goul** [comment]
The wireframes for data import is ready for a final review, and as agreed during our status talk I will tag you all in here and leave a link to 
@philter87 @signekb @lwjohnst86 @K-Beicher 

Figma:
https://www.figma.com/file/czeKwMxVLKPNQDX42eiTxq/Wireframes?type=design&node-id=0%3A1&mode=design&t=ymjeUcfnmaQ81NNx-1

**Comment by signekb** [comment]
Looks good! I have added a comment on the added * for required fields, and whether we need a text or something to make required vs optional fields more clear

**Comment by henrik-goul** [comment]
Thanks @signekb 
I have added a small description text above the table to let the user know the meaning of the asteriks. If the user misses a required field and leaves it empty, the field will light up with an error when the user tries to press "submit", and the user gets a chance to correct the mistake :)

**Comment by lwjohnst86** [comment]
Really nice, had a review of it. Only small comment, more of a thought, is whether the column name should be required or optional, but I don't know my opinion on that right now. We can come back to it later. Looks great otherwise!!

**Comment by henrik-goul** [comment]
@lwjohnst86 Whether the column name should be optional or required is something that we can easily change going forward, so we do not need to make a final decision for now. I will close the issue and design as is then :)
