### ISSUE TITLE
Build html page for viewing (and maybe editing) of data type field in the table extraction output

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#81]
Wireframe (with data type field highlighted): 

![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/f4208128-3afd-401b-83f6-820840a654a1)

With data types as dropdown with the options (as described in #56):
- Numeric
- Date
- Boolean
- Character (text)

**Comment by signekb** [comment]
Selects from beercss seems promising: 
```
<div class="field suffix border round small">
  <select>
    <option>Item 1</option>
    <option>Item 2</option>
    <option>Item 3</option>
  </select>
  <i>arrow_drop_down</i>
</div>
```
