### ISSUE TITLE
[discussion]: Rename all `verify_` functions to be `check_`?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#825]
### What would you like to discuss?

Given all the discussion/confusing about verify vs validate, maybe it would be easier to rename to something a bit more agnostic, like check. Thoughts?

**Comment by signekb** [comment]
I like `check_`; it's simple. And I can't think of any better alternatives 👍

**Comment by martonvago** [comment]
Hmm, actually for the function names themselves maybe I prefer `check` after all, because I feel like it's more of a synonym for verify/validate than `confirm`

**Comment by lwjohnst86** [comment]
We decided, opened #860 to track this
