### ISSUE TITLE
[discussion]: Consider other packages for doing validation work

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#826]
### What would you like to discuss?

Based on some of the issues I noticed with frictionless validating, especially regarding if they need just a file path or what (e.g. in #824), I dug into the source code to understand it better. Turns out, it just gave me some anxiety 😆 it isn't very well designed internally. Plus, the most common bug reports are validation issues: https://github.com/frictionlessdata/frictionless-py/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3Abug and maybe a bit more than a third of total open issues are related to validating. So they clearly have some issues. Combined with the approximately once per week commit frequency they have, resolving those issues might take a while. 

So! I think for validating purposes, we go with a tool that is specifically designed for that. I briefly looked into other packages and found:

- [Pydantic](https://docs.pydantic.dev/latest/) which has nearly 300 million!! Downloads per month!! So very popular and very widely used. And is designed for data validation.
- [Pandera](https://pandera.readthedocs.io/en/stable/index.html) which has 5 million downloads  per month, is designed for data validation of DataFrames, which might be a bit easier to use and specific to our purposes.

Thoughts?

**Comment by martonvago** [comment]
I also had a bit of a look today and the two best fits I found were Pandera (so +1) and [Great Expectations](https://github.com/great-expectations/great_expectations). Of these, Pandera is by far the simpler and lighter one; Great Expectations seems to be more like a whole framework, you can do more with it than what we need (visualisation, dashboards, data source collation etc.). [Here](https://endjin.com/blog/2023/03/a-look-into-pandera-and-great-expectations-for-data-validation)'s an informative article comparing them.

As for Pydantic, isn't that mainly for checking that Python objects (e.g. dictionaries) match a given schema? I think we could use it, but it would involve loading each data row into a Pydantic model, which we will then just discard.

Based on the limited amount of information I have, I'd vote for Pandera! It seems to be optimised for working with tabular data, has many built-in validators specifically for this use case, and supports pandas data frames. All we would need to do is write an adaptor that transforms a table schema (in `datapackage.json`) into a Panderas schema.

**Comment by martonvago** [comment]
So far I've been thinking of validating/verifying tabular data as the use case for the new library, but do we also want to use it for verifying package and resource properties? Because that would be more aligned with the use case for Pydantic, I think. Or there is also [jsonschema](https://github.com/python-jsonschema/jsonschema), which is specifically for validating JSON objects against JSON schemas.

It feels like these are two separate tasks though (checking tabular data vs checking a single JSON object or dictionary), so I raised #830 for the latter.

**Comment by lwjohnst86** [comment]
@martonvago completely agree here! We would realistically need two libraries for it, since it (I assume) would be doing very different things (JSON checks vs DataFrame checks and validation).

**Comment by signekb** [comment]
During the work @martonvago and I did today (#832 #833 ), we encountered more unexpected behaviour from `frictionless`' `validate()` function, so we also talked about that it would be simpler to move away from using the function altogether.

**Comment by martonvago** [comment]
I've been looking a bit more at Pandera, and it supports polars to a large extent 🎉 ! There are [things not (yet) implemented](https://pandera.readthedocs.io/en/stable/index.html#supported-features) though, but I'm not sure how much of a roadblock that is for us. E.g., they can't do schema inference with polars yet, which we would (presumably) use in our `extract_properties_from_file`.

**Comment by lwjohnst86** [comment]
Closed in seedcase-project/decisions#135
