### ISSUE TITLE
Function to run check on inputted (and edited) table extraction metadata whether it is completed or not

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#86]
This function validates the completeness of the table metadata (@signekb believes this might rely on the data model issue #69)

I think this function should check whether all columns have: 
- name (not blank)
- data type (one of the defined data types)
- short description (not blank) 
- allow missing (yes or no)
- allow duplication (yes or no)

**Comment by K-Beicher** [comment]
I've had to allow the description field to contain null values for the editing to work.  It is probably something we can fix later on, but for now it would be good if we can design this function in a way that we can turn individual fields on and off.

**Comment by K-Beicher** [comment]
@lwjohnst86, @signekb. As django is already doing this for us on 'update' should we mark this a low priority?

**Comment by signekb** [comment]
Since it's already handled by Django (at least when it comes to `forms`), we have closed this issue.
