### ISSUE TITLE
Build html page that displays fields that are not completed

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#87]
If users click "Submit" on the page showing the extracted headers and definitions and there are fields that haven't been completed, these will be highlighted: 

![Image](https://github.com/seedcase-project/seedcase-sprout/assets/40836345/de34e9de-ccc2-43f6-bdfa-695f94a6e993)

The functionality for checking whether the table metadata is completed or not is build in #86

**Comment by signekb** [comment]
@K-Beicher is this included with the form validation in #149 , or should I add something more "visual" to highlight all missing fields?

**Comment by signekb** [comment]
This is a nice to have, not a need to have. We'll put this on hold.

**Comment by lwjohnst86** [comment]
given our recent modifications to the UI, and how Django implements forms, this doesn't seem necessary anymore.
