### ISSUE TITLE
[user-story]: Download of table and column metadata

### ISSUE THREAD

**Issue by K-Beicher** [seedcase-project/seedcase-sprout#99]
### What user story would you like to add?

As a (Data)Administrator, I want to be able to download a copy of my table and column metadata in the same format that I completed it in, so that I can edit it offline. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by K-Beicher** [comment]
As described in the next user story, it would be good if we had an option for people to upload a definition straight to Seedcase, bypassing the whole 'upload and analyse the csv' step.

**Comment by lwjohnst86** [comment]
We decided to start the web app from scratch after the major design/architecture decisions and changes we made. No longer relevant.
